name: flutter_ott
description: This is a flutter starter app for quick format builder.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # CUSTOMS
  app_color: ^0.0.7
  auth_management: ^0.1.3
  data_management: ^0.1.1
  flutter_andomie: ^0.5.6-alpha1
  flutter_androssy: ^0.2.8-alpha3
  flutter_app_navigator: ^1.0.1

  # OTHERS
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  go_router: ^10.2.0
  shared_preferences: ^2.2.1
  flutter_animate: ^4.2.0+1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  fluentui_icons: ^1.0.0
  pod_player: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/contents/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/lora/bold.ttf
          weight: 700
        - asset: fonts/lora/bold_italic.ttf
          weight: 700
          style: italic
        - asset: fonts/lora/italic.ttf
          style: italic
        - asset: fonts/lora/medium.ttf
        - asset: fonts/lora/medium_italic.ttf
        - asset: fonts/lora/regular.ttf
        - asset: fonts/lora/semi_bold.ttf
        - asset: fonts/lora/semi_bold_italic.ttf
          style: italic
        - asset: fonts/lora/variable.ttf
        - asset: fonts/lora/variable_italic.ttf
          style: italic

    - family: Arial
      fonts:
        - asset: fonts/arial/bold.ttf
